### ISSUE TITLE
Add options for who to tag.

### ISSUE THREAD

**Issue by Dinomannen** [jacob-keller/L0G-101086#22]
It would be nice with an option to select who gets tagged.
For example.
Only those whose IGN and discord ID is in guild roster in config file.
@here
@everyone
no tagging.
All participants.

**Comment by jacob-keller** [comment]
I'm not sure we can do @everyone or @here

We have to send the discord id for that.

**Comment by jacob-keller** [comment]
Ok, my intention is to add two configurable fields. First, a field which will be additional text to add, which could include discord ids for things like @here or @everything.

Second, a field for configuring whether to show all names, only show the mappings, or show mappings if possible and names otherwise.

This should give maximum flexibility on what to display for a given encounter. Does this sound like it would fulfill your request?

**Comment by Dinomannen** [comment]
For our use only showing mapping is what we want.
But adding opstion to show only names, only mappings, mappings if possible and names otherwise,nothing.
Would cater to most furute cases for folks.

**Comment by jacob-keller** [comment]
This is implemented in release v2.5.0. Please let me know if it works, and if not file a new issue.
